@startuml US1018_SSD

title System Sequence Diagram - US 1017

autonumber

actor "Customer Manager" as cm
participant ":System" as app

activate cm
cm -> app : grade applications
activate app
app --> cm : shows a list of job offers associated\nwith that Customer Manager
deactivate app
cm -> app : picks one
activate app
app --> cm : shows graded applications
deactivate app
deactivate cm

@enduml