@startuml

Package JobOfferAggregate{
    Entity JobOffer {
        <<root entity>>
    }

    Class JobRefCode <<(V, #f09000) Identifier value Object>>{}
    Class JobTitle <<(V,#f04800) value Object>>{}
    Class ContractType  <<(V,#f04800) value Object>>{}
    Class JobMode <<(V,#f04800) value Object>>{}
    Class NumberOfVacancies <<(V,#f04800) value Object>>{}
}

Package PluginAggregate{

    Entity RegisteredPlugin  {
        <<root entity>>
    }

    Class PluginFileName <<(V,#f09000) Identifier value Object>>{}
    Class PluginName <<(V,#f04800) value Object>>{}
    Enum PluginType << enum Object>>{}
}

Package RequirementsSpecification{

    Entity RequirementSpecification  {
        <<root entity>>
    }

    Class RequirementSpecificationDescription <<(V,#f04800) value Object>>{}
    Class RequirementSpecificationAnswer <<(V,#f04800) value Object>>{}
    Class RequirementSpecificationRefCode <<(V,#f09000) Identifier value Object>>{}
}

Package ApplicationAggregate{

    Entity Application  {
        <<root entity>>
    }

    Class ApplicationAttachedFile <<(V,#f04800) value Object>>{}
    Class ApplicationRefCode <<(V,#f09000) Identifier value Object>>{}
    Class ApplicationAttachedFilesLocation <<(V,#f04800) value Object>>{}
    Class InterviewGrade <<(V,#f04800) value Object>>{}
    Class ApplicationState <<(V,#f04800) value Object>>{}
    Class ApplicationEmail <<(V,#f04800) value Object>>{}
    Class Rank <<(V,#f04800) value Object>>{}
}

Class RequirementsAssessment <<(V,#0000FF) value Service>> {}

JobOffer ..> RequirementsAssessment
RequirementsAssessment ..> Application

JobOffer "1" ---- "1" JobRefCode : identifies <
JobOffer "1" ---- "1" JobTitle : describes <
JobOffer "1" ---- "1" ContractType : describes <
JobOffer "1" ---- "1" JobMode : describes <
JobOffer "1" ---- "1" NumberOfVacancies : describes <
JobOffer "1" -- "1" RequirementSpecification : <
JobOffer "1" <-up- "1" CustomerEntity : > "posts"

RequirementSpecification "1" -- "1" RequirementSpecificationDescription : "describes" <
RequirementSpecification "1" -- "1" RequirementSpecificationRefCode : "identifies" <
RequirementSpecificationAnswer "*" -- "1" RequirementSpecification : "describes" >
RequirementSpecification "1" -right- "1" RegisteredPlugin : "configures" <

RegisteredPlugin -- PluginFileName : locates <
RegisteredPlugin -- PluginName : identifies <
RegisteredPlugin -- PluginType : classifies <

Application "*" --> "1" JobOffer : > pertains to
Application "1" - "1" ApplicationEmail : > contains
Application "1" -- "1" ApplicationRefCode : describes <
Application "1" -- "*" ApplicationAttachedFile : > contains
Application "1" -- "1" ApplicationAttachedFilesLocation : > contains
Application "1" -- "1" ApplicationState : > contains
Application "1" -- "1" InterviewGrade : > contains
Application - Rank : describes <

@enduml