@startuml
'https://plantuml.com/class-diagram

autonumber

participant GenericClass as class
participant PersistenceContext as ctx
participant RepositoryFactory as repoFactory
participant GenericRepository as repo


activate class

class -> ctx : repositories()
deactivate class
activate ctx

ctx -> repoFactory : create()

deactivate ctx
activate repoFactory
repoFactory -> repo : generics()
deactivate repoFactory
activate repo

@enduml